import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/components/ReactQueryProvider";
import Header from "@/components/Header/Header";

const montserrat = Montserrat({ subsets: ["latin"], weight: ["300", "500", "600", "700", "900", "400"] });

export const metadata: Metadata = {
  title: "MKS Frontend Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={montserrat.className}>
          <Header />
          {children}
        </body>
      </html>
    </ReactQueryProvider>
  );
}
